feat: voicekick command
arch-community/qbot pull request #225
Opened 2022-10-12 19:55 UTC by gregdan3

The original intention was to entirely remove a user from voice, but that isn't possible with discordrb; see https://github.com/shardlab/discordrb/issues/185

This version moves the user to a specified channel if one is set, to the afk channel if one is set, or throws a failure message otherwise.

2022-10-12 20:02 UTC, anna328p requested changes
Looks great overall! However, probably need to add a permission check of some kind

2022-10-12 20:03 UTC, anna328p commented
really appreciate the en_kawaii translations lol

2022-10-12 20:33 UTC, anna328p requested changes

2022-10-12 20:33 UTC, anna328p commented on modules/util.rb
> +    required_permissions: %i[manage_users]
unfortunately, discordrb [only supports setting one, global string](https://github.com/shardlab/discordrb/blob/43da7657731d2da7ff68c332f6967b9a0f158476/lib/discordrb/commands/command_bot.rb#L243) for this feature, which means localization does not work.

so permission checks usually happen manually ([example](https://github.com/arch-community/qbot/blob/7b217bfc059fa81d06bb6184d30e7b52e77afbf7/modules/colors.rb#L143)).

2022-10-12 20:39 UTC, anna328p commented
the issue is that the message it responds with doesn't get localized because of CommandBot jank

2022-10-12 20:43 UTC, gregdan3 commented
yup- I see it now
tested and pushed

2022-10-12 20:45 UTC, anna328p approved these changes

2022-10-12 20:46 UTC, anna328p commented
the other issue is that qbot ignores commands from other bots. which will be more difficult to resolve

2022-10-12 20:50 UTC, gregdan3 commented
ooo yikes
Where is that logic implemented? We could throw in a bot ID whitelist for the config

2022-10-12 21:10 UTC, anna328p commented
https://github.com/arch-community/qbot/blob/46be0065b333327faeb7700cc3e5394ac0a9ac55/lib/init.rb#L32

2022-10-12 21:13 UTC, anna328p commented
https://github.com/shardlab/discordrb/blob/ac58cf5853c5c5b4948e9a26ab305a203fac5651/lib/discordrb/bot.rb#L1279

2022-10-13 18:35 UTC, anna328p commented
requesting rebase on main

2022-10-13 20:28 UTC, merged