Fix blacklist bypass by blocking `qbot`
arch-community/qbot pull request #57
Opened 2021-03-31 13:44 UTC by FjorgeTheHuman

See issue #56 for the bug report.

P.S. I can't figure out how to not have the second Fjorge when I `git push`

2021-03-31 13:46 UTC, thewarsawpakt commented
> P.S. I can't figure out how to not have the second Fjorge when I git push

You can try github ssh authentication.

2021-03-31 13:46 UTC, FjorgeTheHuman commented
> You can try github ssh authentication.

I tried that and I don't think it worked in the past, unless we're talking about different things.

2021-03-31 13:48 UTC, thewarsawpakt commented
> I tried that and I don't think it worked in the past, unless we're talking about different things.

I've used [this](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh) article recently to get it set up.

2021-03-31 13:57 UTC, FjorgeTheHuman commented
> I've used [this](https://docs.github.com/en/github/authenticating-to-github/connecting-to-github-with-ssh) article recently to get it set up.

I'll take a look later, thanks!

2021-04-01 06:29 UTC, anna328p requested changes

2021-04-01 06:29 UTC, anna328p commented on modules/blacklist.rb
> +      event.respond t('blacklist.unblock', format('<@%s>', event.message.author.id))
Please use `Discordrb::User#mention`

2021-04-01 19:30 UTC, merged