Add quotes module
arch-community/qbot pull request #72
Opened 2021-04-23 17:41 UTC by PioKozi

Aims to add functionality for [quotes](https://github.com/arch-community/qbot/projects/1#card-51249107).

2021-04-24 05:09 UTC, anna328p requested changes
overall good. just a few nitpicks.

2021-04-24 05:09 UTC, anna328p commented on modules/quotes.rb
> +    target_id = Integer(target[3..-2])
[Message#mentions](https://drb.shardlab.dev/main/Discordrb/Message.html#mentions-instance_method)

2021-04-24 05:09 UTC, anna328p commented on modules/quotes.rb
> +      if (m.author.id == target_id) and (not m.from_bot?)
`Array#find`. I also recommend grabbing more history.

2021-04-24 05:09 UTC, anna328p commented on modules/quotes.rb
> +    target_id = Integer(target[3..-2])
Same applies here.

2021-04-24 05:09 UTC, anna328p commented on modules/quotes.rb
> +      quote_list += "id: #{q.id}\n#{q.text}\n"
use map and join here.

2021-04-24 05:09 UTC, anna328p commented on modules/quotes.rb
> +    if quote_list != "" then embed quote_list else embed t('quotes.list.empty', target) end
check for `quotes.size` instead of the resulting string. also try to split if statements into multiple lines

2021-04-24 05:09 UTC, anna328p commented on modules/quotes.rb
> +    target_id = Integer(target[3..-2])
same thing about mentions applies here. i also recommend that if you don't mention a user, use the only specified parameter as the quote id.

2021-04-24 05:09 UTC, anna328p commented on modules/quotes.rb
> +      if result then embed result.text else embed t('quotes.quote.failure', target, quote_id) end
split this into multiple lines

2021-04-24 05:09 UTC, anna328p commented on modules/quotes.rb
> +      results = Quote.where(server_id: event.server.id,
I'm pretty sure active record has a way to find the most recent entry. that would perform a lot better

2021-04-24 05:09 UTC, anna328p commented on modules/quotes.rb
> +    if random_quote then embed random_quote.text else embed t('quotes.rquote.failure', target) end
same as above for this whole command.

2021-04-25 01:14 UTC, anna328p requested changes
After this PR is merged, I'm going to add a helper for commands with a user argument so that they work with pings or IDs, and refactor all the commands (not just here) to use it. Looks mostly good to me. just needs a couple more changes.

2021-04-25 01:14 UTC, anna328p commented on modules/quotes.rb
> +      embed t('quotes.grab.success')
in the confirmation message, send the quote's ID as well

2021-04-25 01:14 UTC, anna328p commented on modules/quotes.rb
> +      embed quotes.map{|q| "#{q.id} : #{q.text}"}.join("\n")
for one-line `map` use ruby 2.7 syntax. also slightly tweak the message:
```ruby
quotes.map { "`#{_1.id}`: #{_1.text}" }.join("\n")
```

2021-04-25 01:16 UTC, anna328p commented
Also run this through rubocop. there's a lot of stuff it will catch

2021-04-25 01:18 UTC, anna328p commented
another thing i forgot: add a schema migration for the new quotes table, add it to schema.rb.

2021-04-25 19:24 UTC, PioKozi commented
By timestamp, do you mean an active record timestamp, or a message timestamp?

2021-04-25 19:25 UTC, anna328p commented
I mean an Active Record timestamp

2021-04-25 20:23 UTC, PioKozi commented
> After this PR is merged, I'm going to add a helper for commands with a user argument so that they work with pings or IDs, and refactor all the commands (not just here) to use it.

Should I get the `target_id`s through a function which will later be replaced in the refactor, or do you intend to do this in one go in the refactor?

2021-04-25 20:27 UTC, anna328p commented
@PioKozi I intend to do this in one go.

2021-04-25 21:54 UTC, anna328p requested changes
looks mostly good to me. only one change i can see

2021-04-25 21:54 UTC, anna328p commented on modules/quotes.rb
> +      quote_exists = Quote.exists?(quote_id)
rewrite this as:

```ruby
if Quote.exists?(quote_id)
  embed Quote.find(quote_id).text
else
  embed t('quotes.quote.failure', quote_id)
end
```

2021-04-26 21:53 UTC, anna328p approved these changes

2021-04-26 21:53 UTC, merged